import Head from 'next/head'

import Layout from '@components/Layout';
import Header from '@components/Header';
import Container from '@components/Container';
import Button from '@components/Button';
import Link from 'next/link';
import styles from '@styles/Page.module.scss'
import { buildImageUrl } from '@lib/cloudinary';
import {
  ApolloClient,
  InMemoryCache,
  ApolloProvider,
  useQuery,
  gql
} from "@apollo/client";
import client from '@lib/appolo_client';




export default function Category({ products, category }) {

  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Container>
        <h1>{category.name}</h1>

        <h2>Products</h2>

        <ul className={styles.products}>
          {products.map((product) => {
            const imageUrl = buildImageUrl(product.image.public_id).resize('w_900,h_900').toURL();
            const { image, name, price, slug, id } = product;

            return (

              <li key={id}>
                <Link href={`/products/${slug}`}>
                  <a>
                    <div className={styles.productImage}>
                      <img width="900" height="900" src={imageUrl} alt="" />
                    </div>
                    <h3 className={styles.productTitle}>
                      {name}
                    </h3>
                    <p className={styles.productPrice}>
                      ${price}
                    </p>
                  </a>
                </Link>
                <p>
                  <Button

                    className={`snipcart-add-item`}
                    data-item-id={slug}
                    data-item-name={name}
                    data-item-price={price}
                    data-item-url={`/products/${slug}`}
                    data-item-image={image.url}
                  >
                    Add to Cart
                  </Button>
                </p>
              </li>
            );
          })}

        </ul>
      </Container>
    </Layout>
  )
}



export async function getStaticPaths({ locales }) {


  const data = await client.query({
    query: gql`
    query PageCategories {
  categories {
    id
    name
    slug
    
  }
}

    `
  });


  const paths = data.data.categories.map(category => ({
    params: {
      categorySlug: category.slug

    }
  }))

  return {
    paths: [
      ...paths,
      ...paths.flatMap(path => {
        return locales.map(locale => {
          return {
            ...path,
            locale
          }
        })
      })
    ],
    fallback: false
  }
}


export async function getStaticProps({ params }) {
  const client = new ApolloClient({
    uri: 'https://api-ap-south-1.graphcms.com/v2/cl40x354j2l2q01w69445fgea/master',
    cache: new InMemoryCache()
  });
  const data = await client.query({
    query: gql`
   query CategoryQuery($slug: String = "") {
  category(where: {slug: $slug}) {
    name
    slug
    id
    products {
      id
      image
      name
      price
      slug
      description {
        html
      }
    }
  }
}
    `,
    variables: {
      slug: params.categorySlug
    }
  });

  const category = data.data.category;


  return {
    props: {
      category,
      products: category.products
    }
  }
}